[versions]
activityKtx = "1.9.1"
#noinspection GradleDependency
appcompat = "1.6.1"
constraintlayout = "2.1.4"
coreKtx = "1.13.1"
espressoCore = "3.6.1"
fresco = "3.1.3"
inferAnnotation = "0.18.0"
junit = "4.13.2"
junitVersion = "1.2.1"
material = "1.12.0"

[libraries]
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
animated-webp = { module = "com.facebook.fresco:animated-webp", version.ref = "fresco" }
fresco = { module = "com.facebook.fresco:fresco", version.ref = "fresco" }
imagepipeline-okhttp3 = { module = "com.facebook.fresco:imagepipeline-okhttp3", version.ref = "fresco" }
infer-annotation = { module = "com.facebook.infer.annotation:infer-annotation", version.ref = "inferAnnotation" }
junit = { module = "junit:junit", version.ref = "junit" }
material = { module = "com.google.android.material:material", version.ref = "material" }
webpsupport = { module = "com.facebook.fresco:webpsupport", version.ref = "fresco" }

[plugins]
